name: yoldashapp
description: Azərbaycanı bizimlə gəzin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+40

environment:
  sdk: '>=3.0.6 <4.0.0'
# sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  http: ^0.13.3
  url_launcher: ^6.1.12
  flutter_feather_icons: ^2.0.0+1
  get: ^4.6.5
  pin_code_fields: ^8.0.1
  font_awesome_flutter: ^10.5.0
  # flutter_credit_card: ^3.0.7
  line_icons: ^2.0.3
  intl: ^0.18.1
  dash_flags: ^0.1.1
  carousel_slider: ^4.2.1
  intl_phone_field: ^3.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  webview_flutter: ^4.2.3
  flutter_time_picker_spinner: ^2.0.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.0
  flutter_polyline_points: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  map_launcher: ^2.5.0+1
  flutter_svg: ^2.0.7
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  # web_socket_channel: ^2.4.0
  double_back_to_close_app: ^2.1.0
  # pusher_channels_flutter: ^2.2.0
  image: ^4.1.3
  connectivity_plus: ^5.0.1
  flutter_local_notifications: ^16.2.0
  app_tracking_transparency: ^2.0.4
  # zego_uikit_prebuilt_call: ^3.17.9
  # flutter_screenutil: ^5.9.0
  # zego_uikit_signaling_plugin: ^2.6.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # image_path: "assets/images/yoldash_favicon_bg_transparent_no_alpha.png"
  remove_alpha_ios: true
  image_path: "assets/images/yoldash_favicon_bg_green.png"
  min_sdk_android: 20

flutter:

  uses-material-design: true

  assets:
   - assets/images/

